name: WGJails
main: de.bangl.WGJails.WGJailsPlugin
description: Multi jail system, using WorldGuard regions. based on SwornJail by "t7seven7t".
version: 0.1

authors: [ t7seven7t, BangL ]
depend: [ WorldGuard, WGCustomFlags, WGRegionEvents ]
softdepend: [ WorldEdit, Vault, WGCommandFlags ]

commands:
    jail:
        description: Jails a player.
        permission: wgjails.jail
        usage: /<command> <player> <time> <reason>
    unjail:
        description: Unjails a player.
        permission: wgjails.unjail
        usage: /<command> <player>
    jailcheck:
        description: Checks a player's jail status.
        permission: wgjails.check
        usage: /<command> <player>
    jailmute:
        description: Mutes a jailed player.
        permission: wgjails.mute
        usage: /<command> <player>
    jailset:
        description: Set the spawn points of the jail.
        permission: wgjails.set
        usage: |
                Usage:
                /<command>
                /<command> cancel
    jailstatus:
        description: Check your jail status.
        permission: wgjails.status
        usage: /<command>
    jailhelp:
        description: Shows jail help.
        permission: wgjails.help
        usage: /<command>
permissions:
    wgjails.admin:
        description: Gives access to all commands.
        children:
            wgjails.canusecommands: true
            wgjails.moderator: true
            wgjails.set: true
            wgjails.build: true
    wgjails.moderator:
        description: Gives access to moderator commands.
        children:
            wgjails.unjail: true
            wgjails.jail: true
            wgjails.check: true
            wgjails.mute: true
            wgjails.modify.time: true
            wgjails.modify.reason: true
            wgjails.default: true
    wgjails.default:
        description: Gives access to default player commands.
        children:
            wgjails.status: true
            wgjails.help: true
    wgjails.jail:
        description: Gives access to jail command.
        default: op
    wgjails.unjail:
        description: Gives access to unjail command.
        default: op
    wgjails.check:
        description: Gives access to jailcheck command.
        default: op
    wgjails.mute:
        description: Gives access to mute command.
        default: op
    wgjails.set:
        description: Gives access to jailset command.
        default: op
    wgjails.status:
        description: Gives access to jailstatus command.
        default: true
    wgjails.help:
        description: Gives access to help command.
        default: true